# The content of the Dockerfile is currently commented out. 
# If you want to create a Docker image for your secure application.
# I have directly used the existing third party docker image directly from the dockerhub in the Jenkinsfile-secure. 
# you can use the following Dockerfile content:
# 
# FROM node:12
# WORKDIR /app
# COPY . .
# CMD ["sh", "-c", "echo Running secure app"]